import GlobalState from "@/context";
import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/context/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalState>
          <Providers>{children}</Providers>
        </GlobalState>
      </body>
    </html>
  );
}
